### ISSUE TITLE
Does not work on IE

### ISSUE THREAD

**Issue by mohitdia** [ifwe/infinite-scroll#10]
The infinite scroll does not work on IE because the source uses scrollY property on the window object which is not supported by IE(https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY). Instead pageYOffset should be used for IE > 9.

Recommended change:

```javascript
-  var windowBottom = windowHeight + win[0].scrollY;'
+  var windowBottom = windowHeight + (win[0].scrollY || win[0].pageYOffset);
```

**Comment by ndickiso** [comment]
+1

**Comment by philipp-unger** [comment]
+1

**Comment by djvirgen** [comment]
Thanks for this! I can get a fix out later today.

**Comment by djvirgen** [comment]
Version 1.1.1 has been pushed to master, but I need to update the bower registry to point to our new repo (we switch from `tagged/infinite-scroll` to `ifwe/infinite-scroll`). Thanks for the bug report and fix!

**Comment by djvirgen** [comment]
Version 1.1.1 has been published to bower. Feel free to open another issue if the problem returns.
