### ISSUE TITLE
multiple ajax calls getting fired during initial page load

### ISSUE THREAD

**Issue by nivincp** [ifwe/infinite-scroll#15]
var api_url = 'http://localhost/myapp/';

app.controller('Users', function ($scope, $http) {
    $scope.page = 0;
    $scope.items = [];
    $scope.fetching = false;
    $scope.disabled = false;

```
// Fetch more items
$scope.getMore = function() {
    $scope.page++;
    $scope.fetching = true;
    var end_point = api_url + 'users/index/' + $scope.page;
    console.log(end_point);
    $http.get(end_point).then(function(items) {
        $scope.fetching = false;
        if (items.data.length) {
            $scope.items = $scope.items.concat(items.data);
        } else {
            $scope.disabled = true;
        }
    });
};
```

});

The above script seems to fire end_points twice during the initial page load, any ideas? Here is the HTML

`<div class="users">
    <div class="list-group" tagged-infinite-scroll="getMore()" tagged-infinite-scroll-disabled="fetching || disabled">
        <a ng-repeat="item in items" href="#businesses/{{ item.marketing_code }}" class="list-group-item">
            <span class="users-name">
                {{ item.marketing_code }} {{ item.user_name}}
            </span>
            <span class="glyphicon glyphicon-menu-right pull-right"></span>
        </a>
        <div class="list-group-item text-center" ng-show="fetching">
            Loading...
        </div>
    </div>
</div>`

**Comment by Fayozjon** [comment]
Same issue right here
even if attribute scroll-distance included its firing till the end

**Comment by darrylsepeda** [comment]
I experiencing same issue
its fired three times on initial and not working anymore after that.
Is there any solution regarding this?

**Comment by TysonAndre** [comment]
This is odd. The README suggests setting `$scope.fetching = true;` to ensure that the library doesn't pick it up.

However, https://github.com/ifwe/infinite-scroll/blob/master/src/taggedInfiniteScroll.js does not reference the member variable `fetching` anywhere. Is this up to date?

A possible patch would be adding this after https://github.com/ifwe/infinite-scroll/blob/master/src/taggedInfiniteScroll.js#L27-L30

```javascript
 // Do nothing if currently fetching (Or if last fetch resulted in an error)
if (scope.fetching) {
    return;
}
````
